// Auto-generated by build_contexts.py. Do not edit by hand.
export const contexts = {
  "thoughts are just air": {
    "sourceFile": "Great Trees Society/The little death.txt",
    "contextLines": [
      "That was his low wisdom, held close to his roots. His high wisdom was long to say in the tongue of trees, and hard to read for those not trained in the language of the trees.",
      "",
      "As each branch split, each meaning grew. Each sentence started with the original word, woven into the base of the trunk, and grew steadily out through the deep boughs and splintered into twigs. Some, fragments of thoughts, were just the start of the Long Word, and would be years before their clarity came.",
      "",
      "Others were short, simple recordings of the lessons of the day, the simple lessons of how to grow tall, seek light, provide shelter. Some looked at the contortions for meaning, but there were few now who knew how to read those kinds of stories."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        306
      ]
    ]
  },
  "whispered filament silvered to light": {
    "sourceFile": "Stand and see whispered filament.txt",
    "contextLines": [
      "Stand and see whispered filament ",
      "Silvered to light ",
      "the rocks and rocks and rocks ",
      "Tiny glowing the rocks are silvered symphony a dance of the once heard now seen by some seen and not heard light dance we see and see "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        14,
        33
      ],
      [
        0,
        17
      ]
    ]
  },
  "the darkness had flown": {
    "sourceFile": "Demon.txt",
    "contextLines": [
      "",
      "",
      "Matt’s shriek of pain from the sharp of the knife turns to terror. He drops the knife and reversed from the room. The blood had gone. There was no red left in the room. The darkness had flown across the room ",
      "",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        169,
        191
      ]
    ]
  },
  "faded from view": {
    "sourceFile": "Time in a Fig Grove.txt",
    "contextLines": [
      "And he looked down the Long Years,",
      "And the Grove grew and grew and grew",
      "And then faded from view.",
      "Then came a house.",
      "Then a hill."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        9,
        24
      ]
    ]
  },
  "sun chasing luminance": {
    "sourceFile": "Hark my love.txt",
    "contextLines": [
      " onto that hillside",
      "Look at it glow, ",
      " sun chasing luminance ",
      " eyes chasing the sky",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        1,
        22
      ]
    ]
  },
  "flecks of power in the air": {
    "sourceFile": "He watched flecks of power in the air.txt",
    "contextLines": [
      "He watched flecks of power in the air ",
      "They hung like spiders ",
      "Swinging on their thread "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        11,
        37
      ]
    ]
  },
  "invisible to all there was": {
    "sourceFile": "He watched flecks of power in the air.txt",
    "contextLines": [
      "Swinging on their thread ",
      "Invisible to life ",
      "Invisible to all there was. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        26
      ]
    ]
  },
  "dissipates like smoke": {
    "sourceFile": "Inbox/The lands roll into each other.txt",
    "contextLines": [
      "The lands roll into each other ",
      "Like smoke, the anger of the people rolls into the grassy sea ",
      "Dissipates, like smoke ",
      "Churned up again the dust of cars, transport to make the world red/grey / the mialsma left when the world paints itself grey "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        22
      ]
    ]
  },
  "memory flickers": {
    "sourceFile": "Testorone.txt",
    "contextLines": [
      "Joy, happy, sticky floors and bright lights. The KKK like I never imagined.",
      "",
      "Memory flickers. ",
      "",
      "Ambika. Jumping the butt in door."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        15
      ]
    ]
  },
  "shuffle off o' mortal coil": {
    "sourceFile": "In the falling of the night.txt",
    "contextLines": [
      "Was it my own thought making its way back to me?",
      "",
      "Shuffle off, o mortal coil, your time is no more."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        26
      ]
    ]
  },
  "mist flowing towards the door": {
    "sourceFile": "Demon.txt",
    "contextLines": [
      "The room began to darken as the mist spread and ate the light. Matt could see the mist flowing towards his closet, towards his bed, towards his desk, towards his dresser. ",
      "",
      "In his terror, he had fallen/sat down, and his body was blocking the mist from flowing towards the door behind him. ",
      "",
      "His hand was turning black, or the blood was coming out black as it vaporized as it came out of his palm. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        116
      ]
    ]
  },
  "protective womb mimicry": {
    "sourceFile": "the white ghost of memory.txt",
    "contextLines": [
      "the white ghost of memory",
      "protective womb",
      "mimicry  "
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        0,
        15
      ],
      [
        0,
        7
      ]
    ]
  },
  "as it coalesces from eternity": {
    "sourceFile": "Inspiration is.txt",
    "contextLines": [
      "> Kisses your lips ",
      "> ",
      "> as it ",
      "> ",
      "> coalesces "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        8
      ]
    ]
  },
  "the white ghost of memory": {
    "sourceFile": "the white ghost of memory.txt",
    "contextLines": [
      "the white ghost of memory",
      "protective womb",
      "mimicry  "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        25
      ]
    ]
  },
  "in the moments between moments": {
    "sourceFile": "I feel most inspired.txt",
    "contextLines": [
      "I feel most inspired ",
      "",
      "In the moments ",
      "",
      "Between moments ",
      "",
      "Transitions they called it"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 3,
    "fragmentCharRanges": [
      [
        0,
        15
      ],
      [
        0,
        0
      ],
      [
        0,
        15
      ]
    ]
  },
  "power dissipates": {
    "sourceFile": "Come and whisper me this story.txt",
    "contextLines": [
      "The echo of power is power ",
      "",
      "Power dissipates, it does not disappear",
      "",
      "If I believe is not power "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        16
      ]
    ]
  },
  "the echo of power is power": {
    "sourceFile": "Come and whisper me this story.txt",
    "contextLines": [
      "/of long crashing boughs and strangers in the mist/",
      "",
      "The echo of power is power ",
      "",
      "Power dissipates, it does not disappear"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        26
      ]
    ]
  },
  "soft and warm like a memory": {
    "sourceFile": "There was such a.txt",
    "contextLines": [
      "this is what ",
      "life should always be ",
      "Soft and warm ",
      "Like a memory ",
      "Made up of a time ",
      "long ago "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        0,
        14
      ],
      [
        0,
        13
      ]
    ]
  },
  "strange haze over the valley": {
    "sourceFile": "California 2.txt",
    "contextLines": [
      "There is a strange haze over the valley ",
      "It reminds me of home ",
      ""
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        11,
        39
      ]
    ]
  },
  "a ghost of ideas long past": {
    "sourceFile": "Hark my love.txt",
    "contextLines": [
      "And every now and again some small glowing white shape",
      "Deigns to join it",
      "A ghost of ideas long past",
      "Or clump of sand",
      "Or plastic bag, the hubris of days long ago"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        26
      ]
    ]
  },
  "pale pink before dawn": {
    "sourceFile": "Did you know there are spiders with only 5 legs.txt",
    "contextLines": [
      "at the time when the bulbuls duet with the sparrows. ",
      "",
      "Did you know? there’s a pale pink before dawn",
      "just a hint of pink ",
      "So hinting you could miss it "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        24,
        45
      ]
    ]
  },
  "the form fades": {
    "sourceFile": "Did you know there are spiders with only 5 legs.txt",
    "contextLines": [
      "Even the fairest of light seem pink by comparison   ",
      "",
      "Did you know? to remember that the form, ",
      "Fades.",
      "",
      "What will "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        31,
        41
      ],
      [
        0,
        5
      ]
    ]
  },
  "this is a world of air": {
    "sourceFile": "Pierre de Coubertin.txt",
    "contextLines": [
      "",
      "Who describes things so ethereal, so floating, so once and done. ",
      "This is a world of air. ",
      "",
      "These words will lose their enshrined meaning, or it will change, or as the letters behind the words contort themselves to be the same shapes in new media, we will find a new shape of meaning in these words. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        22
      ]
    ]
  },
  "gap between breath and emptiness": {
    "sourceFile": "Pierre de Coubertin.txt",
    "contextLines": [
      "",
      "Remember, *beti*, the horror of this world we dream. Every dark moment is here, now, in this one. Find me a moment without an invasion of the sanctity of body, of space, of mind, of thought, of wonder. ",
      "You raise a challenge, *beti*? Will you whisper to me again in the rustling of the pages, the curve of the canvas, the gap between breath and emptiness.",
      "",
      "So we thought, is the way of things."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        119,
        151
      ]
    ]
  },
  "leave wonder wondering": {
    "sourceFile": "Pierre de Coubertin.txt",
    "contextLines": [
      "Oh come, all, let’s see. Will they lift you up so high? Call out in your wonder?",
      "",
      "Leave wonder, wondering.",
      "Stitch my heart with yours and its hard to rip asunder",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        23
      ]
    ]
  },
  "to fade into light": {
    "sourceFile": "There’s something funny about hands.txt",
    "contextLines": [
      "I wonder why or how it is so long, and she created so many ways of moving. Are they even all different?",
      "",
      "To fade into light seems like a gift. I wonder if I need to believe in God to receive it. ",
      "",
      "I wonder about the lighting. And the lights. Why choose lights at all. Bright lights seem to be the provenance of those who have never stopped to think about it. Those who didn’t know there were variations in seeing, the way there are variations in degrees of movement. And life. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        18
      ]
    ]
  },
  "coalesced from eternity made water": {
    "sourceFile": "There’s much that can be done in the 5 minutes before sleep.txt",
    "contextLines": [
      "",
      "You say:",
      "Snowflake, coalesced from eternity, made water in my hands. ",
      "",
      "I say:"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        11,
        46
      ]
    ]
  },
  "sharp strokes and sharp blades": {
    "sourceFile": "I listen.txt",
    "contextLines": [
      "\\",
      "Let the guillotine come in the night\\",
      "Sharp strokes and sharp blades \\",
      "Exhaust not my precious store of hope. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        30
      ]
    ]
  },
  "scars on his wrist burn": {
    "sourceFile": "Burned Invitingly.txt",
    "contextLines": [
      "He feels weird, hearing those words. \\",
      "The pit grows in his stomach\\",
      "and the scars on his wrist burn invitingly. \\",
      "Were they treating Him right?",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        8,
        31
      ]
    ]
  },
  "sinew rots to bone": {
    "sourceFile": "5-7-5.txt",
    "contextLines": [
      "air pulled inward",
      "Devotionals spring forward",
      "Sinew rots to bone",
      "",
      "Page peace pulls"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        18
      ]
    ]
  },
  "skin ready to be torn": {
    "sourceFile": "Your breath comes more shallow and you ask.txt",
    "contextLines": [
      "Their beauty noticed at the last ",
      "Wolves in the fire light ",
      "Skin ready to be torn "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        21
      ]
    ]
  },
  "bones get tired": {
    "sourceFile": "Delicate pieces before the end (2).txt",
    "contextLines": [
      "",
      "To keep living \\",
      "As the bones get tired \\",
      "The indulgences get harder \\",
      "(To swallow / take / survive ) \\"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        7,
        22
      ]
    ]
  },
  "muscles were shaking": {
    "sourceFile": "A tiny bit of witchcraft.txt",
    "contextLines": [
      "The mise en place for dinner prep was done. ",
      "",
      "His muscles were shaking.  He slowly moved along the floor, got up, cut a lemon slice, bit it. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        4,
        24
      ]
    ]
  },
  "cold wind sends hair erect": {
    "sourceFile": "morning.txt",
    "contextLines": [
      "",
      "this moaning induced rage",
      "cold wind sends hair erect, unflexed",
      "so goddamn hard to hear the koels",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        26
      ]
    ]
  },
  "watching the blood / watching it coagulate and flow": {
    "sourceFile": "Crimson tides.txt",
    "contextLines": [
      "Will. Will do it. Tonight. Now.",
      "",
      "It is so distracting though, watching the blood. Watching it coagulate and flow, slowly form drops, and then fall, down to where it hits with terrible violence that destroys its delicate body, and splashes everything with red brilliance.",
      "",
      "That color is forever etched into my mind. The dull crimson glow, winking accusingly in the florescent lights. I see it all again, like a horrible stuck record; it keeps playing. I remember walking into the bathroom, seeing him with the gun in his hand, and speaking those damning words:"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        29,
        79
      ]
    ]
  },
  "bangles clattering in the cold": {
    "sourceFile": "What is a life well spent.txt",
    "contextLines": [
      "",
      "Is it a life of silver and trinkets ",
      "Bangles clattering in the cold",
      "",
      "Is it a life of pleasures and Ecstasy"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        30
      ]
    ]
  },
  "sever the skin and create a book": {
    "sourceFile": "These mornings where.txt",
    "contextLines": [
      "(All around el bed)",
      "",
      "You, honed knife, cut through the flesh of a collapsing tomato. Sever the skin and create a book where there was a being ",
      "(Still astoryin’ about for warmth for the feet!)",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        64,
        96
      ]
    ]
  },
  "intestinal flesh and precluded winter": {
    "sourceFile": "thrum thrum.txt",
    "contextLines": [
      "",
      "We need the harshness of purple",
      "Or a pink to show intestinal flesh and precluded winter",
      " ",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        18,
        55
      ]
    ]
  },
  "dead animals dot the roots": {
    "sourceFile": "I was walking naked on the beach once.txt",
    "contextLines": [
      "It sounds satisfied ",
      "",
      "Dead animals dot the roots of the grass. ",
      "",
      "There’s black that don’t come from fire in this sand. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        26
      ]
    ]
  },
  "so soft so wet so sweet": {
    "sourceFile": "These water nymphs.txt",
    "contextLines": [
      "They come up from the River ",
      "Have you ever felt hands ",
      "So soft",
      "So wet ",
      "So sweet",
      "They kissed your lips as they went by",
      "And looking back you saw"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 3,
    "fragmentCharRanges": [
      [
        0,
        7
      ],
      [
        0,
        7
      ],
      [
        0,
        8
      ]
    ]
  },
  "sharpen the blade": {
    "sourceFile": "We sharpen the blade.txt",
    "contextLines": [
      "We sharpen the blade",
      "*flick flick*",
      "Raised words and sharp voices "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        3,
        20
      ]
    ]
  },
  "pink to show intestinal flesh": {
    "sourceFile": "thrum thrum.txt",
    "contextLines": [
      "",
      "We need the harshness of purple",
      "Or a pink to show intestinal flesh and precluded winter",
      " ",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        5,
        34
      ]
    ]
  },
  "they catch me they caught me": {
    "sourceFile": "These tensions in my back.txt",
    "contextLines": [
      "These tensions in my back",
      "They catch me they caught me they squeeze me ",
      "",
      "I wonder about this path "
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        28
      ]
    ]
  },
  "tensions in my back": {
    "sourceFile": "These tensions in my back.txt",
    "contextLines": [
      "These tensions in my back",
      "They catch me they caught me they squeeze me ",
      ""
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        6,
        25
      ]
    ]
  },
  "pit grows in stomach": {
    "sourceFile": "Burned Invitingly.txt",
    "contextLines": [
      "He feels weird, hearing those words. \\",
      "The pit grows in his stomach\\",
      "and the scars on his wrist burn invitingly. \\",
      "Were they treating Him right?"
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        29
      ]
    ]
  },
  "wolves in the fire light": {
    "sourceFile": "Your breath comes more shallow and you ask.txt",
    "contextLines": [
      "Let the fingers splay",
      "Their beauty noticed at the last ",
      "Wolves in the fire light ",
      "Skin ready to be torn "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        24
      ]
    ]
  },
  "a curtain of snow ready to slip": {
    "sourceFile": "Breathless.txt",
    "contextLines": [
      "Breathless. ",
      "",
      "See a rock bear. And a curtain of snow ready to slip. ",
      "",
      "Was there a curtain of rock before it slipped. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        21,
        52
      ]
    ]
  },
  "earth torn asunder": {
    "sourceFile": "California 3.txt",
    "contextLines": [
      "To say, Look, here is your Birthright. \\",
      "\\",
      "I feel an earth torn asunder \\",
      "A dark valley ready to shift \\",
      "A crack driven by a Parasite \\"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        10,
        28
      ]
    ]
  },
  "slight thud of a delicate body": {
    "sourceFile": "I watched a butterfly today.txt",
    "contextLines": [
      "As I passed by ",
      "Ensconced in perfect climate ",
      "I heard the slight thud ",
      "Of a delicate body ",
      "Caught in the draft of my passage. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        12,
        24
      ],
      [
        0,
        18
      ]
    ]
  },
  "dagger shaped": {
    "sourceFile": "I feel this fear in my heart.txt",
    "contextLines": [
      "Behind the ribs.",
      "It’s a diagonal shape ",
      "dagger shaped ",
      "The breastbone tipped sideways ",
      "And elongated slightly "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        13
      ]
    ]
  },
  "rip tear chew": {
    "sourceFile": "Pierre de Coubertin.txt",
    "contextLines": [
      "",
      "I watch you (us) eat a piece of meat. It’s a heathen revealed. Base animal instincts. You tear at it with your hands. Rip the pieces off the bone. They work their way into your finger nails, you don’t pause to breathe really. It’s rip mouth chew. Rip mouth chew. Like a baby, almost. Or person made baby, by circumstance or situation. ",
      "Rip tear chew. ",
      "Repeat. Repeat. Repeat. The meat, cold from the fridge, oil working its way out of the meat, across the parchment paper and into the box, emblazoned with telltale marks of capitalism at work, branding for the day you find a box, half rotted behind some milk that was too big for the usual shelf and took up more than its allotted share, the oil having soaked its way into the box and the meat is still cold as you rip tear chew. Rip tear mouth chew. Again, again. Again. Again. ",
      "Are you (we (us)) an animal. Would that be so bad, to be an animal. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        13
      ]
    ]
  },
  "bare feet on nails": {
    "sourceFile": "Do you have words you my dear.txt",
    "contextLines": [
      "",
      "Ooo, o’ you most beautiful parts of me,",
      "twirling this dance, bare feet on nails, fire, turned to ash, torture and pain, in memory, remembrance;",
      "",
      "come come come come come come come "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        21,
        39
      ]
    ]
  },
  "twirling a dance of torture": {
    "sourceFile": "Do you have words you my dear.txt",
    "contextLines": [
      "Hearts fly towards you ",
      "You are the most beautiful parts of me",
      "Twirling a dance of torture and pain ",
      "In memory ",
      "And remembrance "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        27
      ]
    ]
  },
  "writhing under you": {
    "sourceFile": "I keep thinking that used to be me.txt",
    "contextLines": [
      "it used to be",
      "it used to be me",
      "writhing under you",
      "or riding beside you",
      " "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        18
      ]
    ]
  },
  "cold in these waters": {
    "sourceFile": "Today.txt",
    "contextLines": [
      "Someday, someway, somehow. ",
      "",
      "It’s cold in these waters ",
      "Though the sea is warm ",
      "and full of fish"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        5,
        25
      ]
    ]
  },
  "tendril a whisper of meat": {
    "sourceFile": "motherfucker.txt",
    "contextLines": [
      "motherfucker",
      "The thought came as he searched the bag, careening through the contents like the bride without her engagement ring from the romp in the pile of straw allusion or real does it matter or the hungry man sifting through the thin soup in search of a remembrance a tendril a whisper of meat. ",
      "motherfucker it whispered again.",
      "It was gone it was gone it was gone it must be gone it seemed right here though it could not be gone and instead just a hidden thing kept safe by a mind desiring to keep things safe things that should not be lost but instead need be kept separate and safe, the providence of children prone to self-harm unaware of the surmountable but overwhelming dangers that remain insurmountable for some of us more height challenged for without the stature of size you remain forever prone to diminutives and elocution more familiar with children then apt or seemingly apt adults. "
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        259,
        284
      ]
    ]
  },
  "breaking up the soil": {
    "sourceFile": "It’s a funny relationship I have.txt",
    "contextLines": [
      "Rrrrrrrrrrrrr",
      "Can you hear the churning ",
      "Breaking up the soil",
      "Making fresh for fresh seeds ",
      "Did more of them die "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        20
      ]
    ]
  },
  "in my back I am the earth": {
    "sourceFile": "Grow Tall My Green Children.txt",
    "contextLines": [
      "Satisfaction in the soul. ",
      "",
      "In my back, I am the earth;",
      "And nothing gives me more joy than the pustules you burst forth. ",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        26
      ]
    ]
  },
  "rooted in a climb of dirt": {
    "sourceFile": "Time in a Fig Grove.txt",
    "contextLines": [
      "And then he saw",
      "A plant",
      "Rooted in a climb of dirt",
      "And the seed of the Grove",
      "Once again, or before?"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        25
      ]
    ]
  },
  "drink deeply of the grass": {
    "sourceFile": "Tree.txt",
    "contextLines": [
      "there, in your curvaceous trunk",
      "",
      "Drink deeply of the grass, sweet elephant queen. ",
      "There is always enough time. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        25
      ]
    ]
  },
  "cedars still walked": {
    "sourceFile": "Have you ever seen.txt",
    "contextLines": [
      "That saw your parents parents parents parents ",
      "Walk across this land ",
      "When the cedars still walked ",
      "A secret gift they gave up ",
      "When the people came to trouble them"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        9,
        28
      ]
    ]
  },
  "grow tall my green children": {
    "sourceFile": "Grow Tall My Green Children.txt",
    "contextLines": [
      "And nothing gives me more joy than the pustules you burst forth. ",
      "",
      "Grow Tall My Green Children.  "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        27
      ]
    ]
  },
  "soldiers fighting against the slow erosion to entropy": {
    "sourceFile": "An ode to aspens.txt",
    "contextLines": [
      "To me,",
      "They’ve always been silent soldiers ",
      "Fighting against the slow erosion to entropy ",
      "It’s been hard watching them fall",
      "These silent soldiers"
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        27,
        36
      ],
      [
        0,
        44
      ]
    ]
  },
  "feathers quiver in the breeze": {
    "sourceFile": "Hello sister.txt",
    "contextLines": [
      "Her white head turns and",
      "I watch her wings ",
      "The feathers quiver in the breeze ",
      "Behind her,",
      "the boys row"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        4,
        33
      ]
    ]
  },
  "still they would remember": {
    "sourceFile": "Ok.txt",
    "contextLines": [
      "And you came 1000 years hence \\",
      "Still there would be",
      "Still they would remember ",
      "Still in ",
      "Still "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        25
      ]
    ]
  },
  "monsoon brings the green": {
    "sourceFile": "Delhi.txt",
    "contextLines": [
      "It’s not longer as polluted as it once was. ",
      "The trees leap forward and burst with life ",
      "The monsoon brings the green to burst forth, and cloak the noise of the millions shadowed in their feet.  "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        4,
        28
      ]
    ]
  },
  "tall trees tall pines": {
    "sourceFile": "Tree.txt",
    "contextLines": [
      "Tall trees, tall pines ",
      "Ever your descendants aspire to height ",
      "Let your curves seduce snakes "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        22
      ]
    ]
  },
  "chained by choices": {
    "sourceFile": "I wonder sometimes.txt",
    "contextLines": [
      "\twhatever behavior to come",
      "\t",
      "Chained by choices ",
      "#chainedchoices",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        18
      ]
    ]
  },
  "my self is bound together": {
    "sourceFile": "God has already wrote such majest.txt",
    "contextLines": [
      "And wonder ",
      "What will I wrot with these few months  ",
      "My self is bound together ",
      "Importable glory in the now ",
      "Would be that I was alive to witness it"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        25
      ]
    ]
  },
  "hold on I still want you": {
    "sourceFile": "Fragments/Hold on I still want you.txt",
    "contextLines": [
      "Hold",
      "",
      "Hold on I still want you",
      "Come back I still need you",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        24
      ]
    ]
  },
  "a morning with the bamboo": {
    "sourceFile": "early morning solace night.txt",
    "contextLines": [
      "Evolved to keep up with our terraforming. ",
      "A volcano, tsunami and hurricane all in one.",
      "What a morning with the bamboo",
      "",
      "And the birds "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        5,
        30
      ]
    ]
  },
  "caught and snared": {
    "sourceFile": "Anuraag oh Anuraag.txt",
    "contextLines": [
      "Anuraag oh Anuraag",
      "Tell me where will you go?",
      "You are caught and snared",
      "Thrashing about ",
      "Will only cause your predicament to grow"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        8,
        25
      ]
    ]
  },
  "these ties that bind": {
    "sourceFile": "These ties that bind.txt",
    "contextLines": [
      "These ties that bind",
      "Make me wonder",
      "What will I be"
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        20
      ]
    ]
  },
  "substances coming into my shoes": {
    "sourceFile": "Breath deep of the trees and dream.txt",
    "contextLines": [
      "There’s small sands of dirt",
      "Rock",
      "Other substances ",
      "Coming into my shoes ",
      "So goddam beautiful the way they ripple and tone ",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        6,
        17
      ],
      [
        0,
        20
      ]
    ]
  },
  "that thing which binds you": {
    "sourceFile": "Large objects exert a gravitational pull.txt",
    "contextLines": [
      "         they bend towards the pull, above.",
      "Issues arises when the connection between objects start to exert its own gravitational                              pull:",
      "that thing which binds you to them is now alive with its own force;",
      "",
      "                                                                   fun fact"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        26
      ]
    ]
  },
  "you are caught and snared": {
    "sourceFile": "Anuraag oh Anuraag.txt",
    "contextLines": [
      "Anuraag oh Anuraag",
      "Tell me where will you go?",
      "You are caught and snared",
      "Thrashing about ",
      "Will only cause your predicament to grow"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        25
      ]
    ]
  },
  "spirit in my bones": {
    "sourceFile": "Cold spirits.txt",
    "contextLines": [
      "Cold spirit",
      "You ruminate ",
      "(in my bones)",
      "Get get get ",
      "(And let me be). "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        13
      ]
    ]
  },
  "pressed against mine": {
    "sourceFile": "I see your body move.txt",
    "contextLines": [
      "I see your body move ",
      "And wonder what it would feel like ",
      "Pressed against mine ",
      "I’m very aware of your movements ",
      "Why do you move so much in these spaces ? "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        20
      ]
    ]
  },
  "your breath caught in my air": {
    "sourceFile": "hey you there.txt",
    "contextLines": [
      "we got stuck together somehow",
      "your shoulder got caught in my  shirt",
      "your breath got caught in my air",
      "",
      "*beat*"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        32
      ]
    ]
  },
  "stitch my heart with yours": {
    "sourceFile": "Pierre de Coubertin.txt",
    "contextLines": [
      "",
      "Leave wonder, wondering.",
      "Stitch my heart with yours and its hard to rip asunder",
      "",
      "Or maybe my heart ’s big enough already "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        26
      ]
    ]
  },
  "touch in a certain way to give remembrance": {
    "sourceFile": "In a way.txt",
    "contextLines": [
      "touch ",
      "\tin a certain way",
      "\t\tto give remembrance ",
      "\t\t\tI don’t know ",
      "\t\t\t\tif I can take "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 3,
    "fragmentCharRanges": [
      [
        0,
        6
      ],
      [
        0,
        17
      ],
      [
        0,
        21
      ]
    ]
  },
  "gravitational pull between us": {
    "sourceFile": "Large objects exert a gravitational pull.txt",
    "contextLines": [
      "time",
      "         they bend towards the pull, above.",
      "Issues arises when the connection between objects start to exert its own gravitational                              pull:",
      "that thing which binds you to them is now alive with its own force;",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        121
      ]
    ]
  },
  "be mine forever never come near me again": {
    "sourceFile": "I’m becoming tuned to a mechanical vibration.txt",
    "contextLines": [
      "Oh, supreme playmate ",
      "Fulfiller of dreams ",
      "Be mine forever never come near me again be mine forever never come near me again be mine forever never come near me again. Be mine forever. Never come near me again. Be mine forever. Never come near me again. Be mine forever. Never come near me again. Be mine forever ",
      "",
      "Then fell my mind "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        40
      ]
    ]
  },
  "dolphins a-dancing": {
    "sourceFile": "The train.txt",
    "contextLines": [
      "Judge and curious ",
      "Observe and recoil ",
      "And then return, to the long visages of the ocean in front, dolphins a-dancing,",
      "And mountains and hills at the back "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        60,
        78
      ]
    ]
  },
  "dancing now on the morning wind": {
    "sourceFile": "Hark my love.txt",
    "contextLines": [
      "Calling their way home ",
      "",
      "It's dancing now, in the morning wind",
      "And every now and again some small glowing white shape",
      "Deigns to join it"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        37
      ]
    ]
  },
  "flutter of the leaves": {
    "sourceFile": "Everywhere I turn.txt",
    "contextLines": [
      "Everywhere I turn",
      "In the flutter of the leaves and the remembrance of your laugh",
      "Everywhere I turn",
      "In the follow of your face and rememberance of a smile"
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        7,
        28
      ]
    ]
  },
  "the mind is adrift": {
    "sourceFile": "By the time of the third sneeze.txt",
    "contextLines": [
      "By the time of the third sneeze ",
      "The mind is adrift ",
      "In a sea ",
      "Of wondering questions "
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        18
      ]
    ]
  },
  "floating down a river": {
    "sourceFile": "I feel a strange sense of deux la veuces.txt",
    "contextLines": [
      "I feel a strange sense of deux la veuces ",
      "As I gaze upon a field of sunflowers ",
      "While floating down a river ",
      "Chasing new experiences ",
      "The signal for wealth better spent "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        6,
        27
      ]
    ]
  },
  "if only I could spin fast enough": {
    "sourceFile": "ariel.txt",
    "contextLines": [
      "made me pick you up",
      "and spin you around",
      "like if only I could spin fast enough",
      "we could outspin the world",
      "I loved you once"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        5,
        37
      ]
    ]
  },
  "leaves dancing a tiny dance": {
    "sourceFile": "Sometimes.txt",
    "contextLines": [
      "‘lo the whole field ’s a’quaver ",
      "\tleaves dancing a tiny dance ",
      "\tfeet so fast double time a’flutter ",
      "wonder:"
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        1,
        28
      ]
    ]
  },
  "swim to me swim to me": {
    "sourceFile": "Out to play he calls them.txt",
    "contextLines": [
      "To your sisters we’ve given meals ",
      "",
      "Swim to me, swim to me, swim to me ",
      "",
      "One, two, they come in a line"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        22
      ]
    ]
  },
  "water nymphs come up from the river": {
    "sourceFile": "These water nymphs.txt",
    "contextLines": [
      "These water nymphs ",
      "",
      "They come up from the River ",
      "Have you ever felt hands ",
      "So soft"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        28
      ]
    ]
  },
  "let be your squeeze": {
    "sourceFile": "These tensions in my back.txt",
    "contextLines": [
      "Let go your catch ",
      "",
      "Let be your squeeze "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        19
      ]
    ]
  },
  "birth me again": {
    "sourceFile": "These water nymphs.txt",
    "contextLines": [
      "Creator, Destroyer, bringer of the Day. ",
      "",
      "Oh, inversion, birth me again, they kissed across my lips ",
      "",
      "Oh inversion, these water nymphs. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        15,
        29
      ]
    ]
  },
  "under a waterfall in the sun": {
    "sourceFile": "Falling in love with who I am vs who I could be.txt",
    "contextLines": [
      "About the sublime joy ",
      "Of being naked ",
      "under a waterfall ",
      "in the sun ",
      "When that someone ",
      "Has only ever known "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        0,
        18
      ],
      [
        0,
        10
      ]
    ]
  },
  "we could outspin the world": {
    "sourceFile": "ariel.txt",
    "contextLines": [
      "and spin you around",
      "like if only I could spin fast enough",
      "we could outspin the world",
      "I loved you once",
      "I hope you knew that"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        26
      ]
    ]
  },
  "sky dreaming lovers enchanted": {
    "sourceFile": "Show to me your stars.txt",
    "contextLines": [
      "Eyes eyes dark eyes dark shadows filter away the light or burn the eyes, we see so little and die just the same. ",
      "",
      "Sky dreaming lovers enchanted star gazing shine bright and diamond diamond diamond what could be harder ",
      "",
      "Command"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        29
      ]
    ]
  },
  "dancing to and fro": {
    "sourceFile": "important my lofe.txt",
    "contextLines": [
      "A once there was a girl ",
      "",
      "Dancing to and fro",
      "",
      "Dancing dancing where ever she would go!"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        18
      ]
    ]
  },
  "whole field a quaver": {
    "sourceFile": "Sometimes.txt",
    "contextLines": [
      "-----",
      "Sometimes \\",
      "Sometimes to watch the whole field a quaver \\",
      "Is to see leaves dancing a tiny dance \\",
      "Feet so fast a flutter \\"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        23,
        43
      ]
    ]
  },
  "I can hear it now": {
    "sourceFile": "I watch the light bounce.txt",
    "contextLines": [
      "And as I focus on it ",
      "Strangely ",
      "I can hear it now ",
      "In a way ",
      "I never could"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        17
      ]
    ]
  },
  "whisk away the warmth": {
    "sourceFile": "Oh curare water.txt",
    "contextLines": [
      "Spring forth from my eyes !",
      "",
      "Whisk away the warmth ",
      "Cool my troubled brow",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        21
      ]
    ]
  },
  "unbidden / tears spring / to my eyes": {
    "sourceFile": "Unbidden tears spring.txt",
    "contextLines": [
      "Unbidden ",
      "tears spring ",
      "To my eyes",
      "To think",
      "What could be mine. "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 3,
    "fragmentCharRanges": [
      [
        0,
        9
      ],
      [
        0,
        13
      ],
      [
        0,
        10
      ]
    ]
  },
  "soft fingers wandering wondering": {
    "sourceFile": "Like drops.txt",
    "contextLines": [
      "Like drops ",
      "You caress ",
      "with soft fingers ",
      "Wandering ",
      "Wondering ",
      "What joy will they leave in their wake ",
      "What travesty "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 3,
    "fragmentCharRanges": [
      [
        5,
        18
      ],
      [
        0,
        10
      ],
      [
        0,
        9
      ]
    ]
  },
  "what a gift to be on an island": {
    "sourceFile": "Today.txt",
    "contextLines": [
      "",
      "Exclaim:",
      "What a gift, to be on an island.",
      "",
      "Exclaim:"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        31
      ]
    ]
  },
  "we frolic wildly": {
    "sourceFile": "Pierre de Coubertin.txt",
    "contextLines": [
      "Let’s go be animals in the night. ",
      "",
      "We frolic wildly. There’s an amusement in an aggressive pantomiming of sex that has existed across generations. We see it reoccur time and time again. Across cultures and situations. Could it be genetic?",
      "",
      "We frolic wildly. Animals in the night."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        16
      ]
    ]
  },
  "come out you play": {
    "sourceFile": "There's a space we make for new lovers.txt",
    "contextLines": [
      "your reality, away",
      "",
      "come out, you, play ",
      "",
      "***"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        19
      ]
    ]
  },
  "dance away the chlorophyll": {
    "sourceFile": "So much this experience happens within ourselves.txt",
    "contextLines": [
      "",
      "Next time:",
      "- come be a leaf spirit, we will dance away the chlorophyl and fight the cellulose for rehearsal: practice day and night till the performance, ultimate performance, the swan will sing and zigging and zagging we will fall and firstly! Nay lastly! time will come due. ",
      "- our time will come due.",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        266
      ]
    ]
  },
  "give me back my memories": {
    "sourceFile": "Testorone.txt",
    "contextLines": [
      "",
      "",
      "Give me back my memories",
      "",
      "Give me the my memory trigger"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        24
      ]
    ]
  },
  "remembrance of your laugh": {
    "sourceFile": "Everywhere I turn.txt",
    "contextLines": [
      "Everywhere I turn",
      "In the flutter of the leaves and the remembrance of your laugh",
      "Everywhere I turn",
      "In the follow of your face and rememberance of a smile"
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        37,
        62
      ]
    ]
  },
  "a time long ago": {
    "sourceFile": "As I sat here.txt",
    "contextLines": [
      "My mind smiled ",
      "And my heart too ",
      "It was a game of a time long ago ",
      "I time when we had wondered ",
      "What we would be "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        17,
        32
      ]
    ]
  },
  "memories you wish you had": {
    "sourceFile": "Delicate pieces before the end.txt",
    "contextLines": [
      "Anymore \\",
      "Look, Remember, Recreate, \\",
      "The memories you wish you had \\",
      "And this joy \\",
      "Delicate pieces \\"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        4,
        29
      ]
    ]
  },
  "lost to a distant memory": {
    "sourceFile": "I try to remind myself.txt",
    "contextLines": [
      "A poem ",
      "On a day when the grey seems uniform ",
      "And the color lost to a distant memory ",
      "Of circumstances ",
      "And what might have been. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        14,
        38
      ]
    ]
  },
  "once we were unforgettable": {
    "sourceFile": "Hello again.txt",
    "contextLines": [
      "*once we were feared*",
      "discipline, respect, brotherhood",
      "*once we were unforgettable*",
      "courage",
      "*once we were*"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        1,
        27
      ]
    ]
  },
  "who mourns a lost word": {
    "sourceFile": "Book.txt",
    "contextLines": [
      "And his words grew shorter. And phrases were forgotten. And the his delight in the beauty of the art of language, grew to be a joy in clarity of thought.",
      "",
      "Who mourns a lost word? Who remembers, when a word has been lost? ",
      "",
      "If there was Truth, then the perfect Chair must exist too. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        22
      ]
    ]
  },
  "something long thought forgotten": {
    "sourceFile": "Freedom, yet unabigred.txt",
    "contextLines": [
      "Grey and long before me, \\",
      "I panged in my stomach \\",
      "Something long thought forgotten. \\",
      "",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        32
      ]
    ]
  },
  "color lost to a distant memory": {
    "sourceFile": "I try to remind myself.txt",
    "contextLines": [
      "A poem ",
      "On a day when the grey seems uniform ",
      "And the color lost to a distant memory ",
      "Of circumstances ",
      "And what might have been. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        8,
        38
      ]
    ]
  },
  "words we left when we left": {
    "sourceFile": "Willows.txt",
    "contextLines": [
      "creep down ",
      "holding up",
      "these words",
      "we left ",
      "when we left ",
      "ourselves",
      "for "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 3,
    "fragmentCharRanges": [
      [
        6,
        11
      ],
      [
        0,
        8
      ],
      [
        0,
        12
      ]
    ]
  },
  "when you were young": {
    "sourceFile": "When you were young.txt",
    "contextLines": [
      "When you were young ",
      "You got to try on different identities ",
      "To act, to play, to try this face with these people "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        19
      ]
    ]
  },
  "sometimes good morning means goodbye": {
    "sourceFile": "When you live in India.txt",
    "contextLines": [
      "I don’t have anything else to say ",
      "But sometimes good morning means hello",
      "Sometimes good morning means goodbye ",
      "And sometimes it means I don’t have anything else to say ",
      "But hi hi hi hi hi "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        36
      ]
    ]
  },
  "there was joy once": {
    "sourceFile": "Joy/Out of many, one.txt",
    "contextLines": [
      "",
      "Today:",
      "There was joy, once.",
      "",
      "There was life, once."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        19
      ]
    ]
  },
  "everything I build will turn to dust": {
    "sourceFile": "A final thought.txt",
    "contextLines": [
      "",
      "I will die. ",
      "Everything I build will turn to dust ",
      "Everything I do will be forgotten. ",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        36
      ]
    ]
  },
  "relics of my heart": {
    "sourceFile": "In empty shelves.txt",
    "contextLines": [
      "or ",
      "other ",
      "relics ",
      "of ",
      "my heart. ",
      "your time was long ago. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 3,
    "fragmentCharRanges": [
      [
        0,
        7
      ],
      [
        0,
        3
      ],
      [
        0,
        8
      ]
    ]
  },
  "these shadows will be all that remain": {
    "sourceFile": "In so far as there is love.txt",
    "contextLines": [
      "Take heed, my captain ",
      "This light ahead is too harsh ",
      "These shadows will be all that remain.",
      "",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        37
      ]
    ]
  },
  "remembrance owned by others": {
    "sourceFile": "Kashmir.txt",
    "contextLines": [
      "I search ",
      "Memories mine own ",
      "Remembrance owned by others,",
      "That which was before ",
      "(Or as I willed it to be)"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        27
      ]
    ]
  },
  "memories mine own": {
    "sourceFile": "Kashmir.txt",
    "contextLines": [
      "‘Has such a thing been seen before’",
      "I search ",
      "Memories mine own ",
      "Remembrance owned by others,",
      "That which was before "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        17
      ]
    ]
  },
  "their forever why": {
    "sourceFile": "These water nymphs.txt",
    "contextLines": [
      "They kissed your lips as they went by",
      "And looking back you saw",
      "Their forever Why",
      "",
      "Creator, Destroyer, bringer of the Day. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        17
      ]
    ]
  },
  "it reminds me of home": {
    "sourceFile": "California 2.txt",
    "contextLines": [
      "There is a strange haze over the valley ",
      "It reminds me of home ",
      "",
      ""
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        21
      ]
    ]
  },
  "creeping death laughing all the while": {
    "sourceFile": "California 2.txt",
    "contextLines": [
      "It reminds me of home",
      "",
      "\tcreeping death, laughing all the while",
      "",
      "It reminds me of home"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        1,
        39
      ]
    ]
  },
  "morning of the small birds": {
    "sourceFile": "Today.txt",
    "contextLines": [
      "",
      "We are past ",
      "the morning of the small birds",
      "into the mourning of the crows ",
      "or is it ravens "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        4,
        30
      ]
    ]
  },
  "mourning of the crows": {
    "sourceFile": "Today.txt",
    "contextLines": [
      "We are past ",
      "the morning of the small birds",
      "into the mourning of the crows ",
      "or is it ravens ",
      "The caw of one seems as harsh as the other "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        9,
        30
      ]
    ]
  },
  "is that yours or is that mine": {
    "sourceFile": "hey you there.txt",
    "contextLines": [
      "",
      "*beat*",
      "\t\t\t\t\t\t\tis that yours or is that mine",
      "",
      "*beat*"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        7,
        36
      ]
    ]
  },
  "it used to be me": {
    "sourceFile": "I keep thinking that used to be me.txt",
    "contextLines": [
      "it used to be",
      "it used to be me",
      "writhing under you",
      "or riding beside you"
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        16
      ]
    ]
  },
  "fear always eaten moments of glory": {
    "sourceFile": "There is a memory I have a day I once got lost.txt",
    "contextLines": [
      "",
      "",
      "Perhaps that moment that followed that glorious few forgotten moments of wonder on that swing ate those moments of glory. Hasn’t fear always eaten moments of glory? Hasn’t wonder always been subjugated by shame? ",
      "",
      "Shame came calling, when the world bore witness to my mother’s fear. Wonder, fear and the rush of warmth masquerading as joy as equilibrium drives to be restored when the cause has been rectified. Blessed we are when we are young, that the artifacts of these moments are swept up easily. Age leaves more and more notches and creases, places to gather detritus, harder for equilibrium to be restored."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        129,
        163
      ]
    ]
  },
  "today is a memory that someone dreamed up": {
    "sourceFile": "I’ve heard the sound of your breath.txt",
    "contextLines": [
      "Let us sleep baby and dream",
      "Tomorrow is here and ",
      "Today is a memory ",
      "That someone dreamed up ",
      "While planning for tomorrow ",
      "Yesterday  "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        0,
        18
      ],
      [
        0,
        23
      ]
    ]
  },
  "this moment this one": {
    "sourceFile": "Blessed.txt",
    "contextLines": [
      "To know ",
      "that this thing ",
      "This moment ",
      "This one ",
      "Is mine",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        0,
        12
      ],
      [
        0,
        8
      ]
    ]
  },
  "forever is now": {
    "sourceFile": "Who are we.txt",
    "contextLines": [
      "And then remember ",
      "Eternity is in this moment ",
      "And forever is now. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        4,
        18
      ]
    ]
  },
  "today is enough": {
    "sourceFile": "Song of Tomorrow.txt",
    "contextLines": [
      "Oh, you, Song of Tomorrow,",
      "Get out of here. \\",
      "Today is enough \\",
      "Today is all we can manage \\",
      "Today is all we can need."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        15
      ]
    ]
  },
  "moments of grace": {
    "sourceFile": "A final thought.txt",
    "contextLines": [
      "A final thought :",
      "",
      "Though India isn't exactly a place to be young and pretty and single and in your twenties in the time of PrEp.... I have found those moments of grace; instants where you are completely happy. Only that and nothing else. ",
      "",
      "What is a well lived life but a collection of moments of grace."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        133,
        149
      ]
    ]
  },
  "alive alive we live": {
    "sourceFile": "Dandelion light.txt",
    "contextLines": [
      "Let the memory forget the in between the memory will forget forget forget ",
      "Those moments that existed in between ",
      "Alive alive we live for those moments that make us alive ",
      "We can’t trust these things that make their own light ",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        19
      ]
    ]
  },
  "pink fucking mountains": {
    "sourceFile": "In green hills I heard a rumor that there were pink mountains.txt",
    "contextLines": [
      "Pink mountains. ",
      "That’s what they told me, and goddamn if they weren’t there. ",
      "Pink fucking mountains. ",
      "Homeless, they said. Homeless, they heard. Homeless, should we consider, it. ",
      "How many states of being are there, that we might consider which ones we choose to be, better. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        22
      ]
    ]
  },
  "light was born": {
    "sourceFile": "inhale, Deeply My.txt",
    "contextLines": [
      "----",
      "Out of Grace & Beginning ",
      "Light was born ",
      "Prone to frolic",
      "He graced us. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        14
      ]
    ]
  },
  "the sublime joy of being naked": {
    "sourceFile": "Falling in love with who I am vs who I could be.txt",
    "contextLines": [
      "Falling in love with who I could be ",
      "Is like telling someone ",
      "About the sublime joy ",
      "Of being naked ",
      "under a waterfall ",
      "in the sun "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        6,
        22
      ],
      [
        0,
        14
      ]
    ]
  },
  "I forgot I was magic": {
    "sourceFile": "￼I forgot I was magic.txt",
    "contextLines": [
      "￼I forgot I was magic ",
      "",
      "athelas in my hands, bringing healing"
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        1,
        21
      ]
    ]
  },
  "here you come here you come": {
    "sourceFile": "And now that we walk in these days of light.txt",
    "contextLines": [
      "Days of light, days of pride, days of sun. ",
      "",
      "Here you come, here you come, here you come. ",
      "",
      "Be proud, child, for I am proud of you. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        28
      ]
    ]
  },
  "this is why we live": {
    "sourceFile": "to find love when you least expect it.txt",
    "contextLines": [
      "",
      "",
      "this is why we live."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        19
      ]
    ]
  },
  "cold feet find wonder": {
    "sourceFile": "Show me filament and pull my attention.txt",
    "contextLines": [
      "chase some light and find wonder",
      "Chase chase chase ",
      "Cold feet find wonder "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        21
      ]
    ]
  },
  "light is designed for wonder": {
    "sourceFile": "Show me filament and pull my attention.txt",
    "contextLines": [
      "Show me filament and pull my attention light light there is so much light pulling here and light pulling to there and can you but wonder this is a place with so much wonder the light is designed for wonder ",
      "The shadows designed for wonder ",
      "The light chasing chasing chasing chasing wonder "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        177,
        205
      ]
    ]
  },
  "chase some light and find wonder": {
    "sourceFile": "Show me filament and pull my attention.txt",
    "contextLines": [
      "The shadows designed for wonder ",
      "The light chasing chasing chasing chasing wonder ",
      "chase some light and find wonder",
      "Chase chase chase ",
      "Cold feet find wonder "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        32
      ]
    ]
  },
  "top of my head is tingling": {
    "sourceFile": "It is that the very top of my head is tingling.txt",
    "contextLines": [
      "It is that the very top of my head is tingling \\",
      "As I look out \\",
      "And see \\"
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        20,
        46
      ]
    ]
  },
  "blessed to see movement": {
    "sourceFile": "Blessed.txt",
    "contextLines": [
      "Blessed",
      "To see movement before our eyes",
      "To know ",
      "that this thing "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        0,
        7
      ],
      [
        0,
        15
      ]
    ]
  },
  "completely happy only that": {
    "sourceFile": "A final thought.txt",
    "contextLines": [
      "A final thought :",
      "",
      "Though India isn't exactly a place to be young and pretty and single and in your twenties in the time of PrEp.... I have found those moments of grace; instants where you are completely happy. Only that and nothing else. ",
      "",
      "What is a well lived life but a collection of moments of grace."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        174,
        201
      ]
    ]
  },
  "this is why we are alive": {
    "sourceFile": "I let my eyes feast on you.txt",
    "contextLines": [
      "We are reminded ",
      "Oh, this is why ",
      "This is why we are alive  "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        24
      ]
    ]
  },
  "became wonder": {
    "sourceFile": "Night song.txt",
    "contextLines": [
      "Night song",
      "",
      "Became Wonder ",
      "",
      "Changed "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        13
      ]
    ]
  },
  "life and love be all you do": {
    "sourceFile": "Hark my love.txt",
    "contextLines": [
      "Dream, dream dream, little tree",
      "",
      "Life and love be all you do"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        27
      ]
    ]
  },
  "I see yellow in the green": {
    "sourceFile": "I was walking naked on the beach once.txt",
    "contextLines": [
      "The longer you look at a uniform thing ",
      "The less uniform your mind lets you see it as ",
      "I see yellow in the green",
      "And streaks of color ",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        25
      ]
    ]
  },
  "eyes chasing the sky": {
    "sourceFile": "Hark my love.txt",
    "contextLines": [
      "Look at it glow, ",
      " sun chasing luminance ",
      " eyes chasing the sky",
      "",
      "That tree don't care one bit that its hill is a mountain"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        1,
        21
      ]
    ]
  },
  "child of wonder": {
    "sourceFile": "I saw something beautiful today.txt",
    "contextLines": [
      "God bless you",
      "Child of creation",
      "Child of wonder",
      "Child of tears"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        15
      ]
    ]
  },
  "shimmer me brighter": {
    "sourceFile": "I saw something beautiful today.txt",
    "contextLines": [
      "So innocent is life ",
      "",
      "Oh, you shimmer of Red.  Shimmer me brighter, you. ",
      "",
      "Shimmer me wonder, you. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        25,
        44
      ]
    ]
  },
  "shimmer of red against the sun": {
    "sourceFile": "I saw something beautiful today.txt",
    "contextLines": [
      "It gives me shivers to think of it ",
      "",
      "a shimmer of red against the sun",
      "",
      "who knew you could find something so pretty"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        2,
        32
      ]
    ]
  },
  "firstly you are first": {
    "sourceFile": "So much this experience happens within ourselves.txt",
    "contextLines": [
      "------",
      "Firstly! Firstly! Firstly you are first.",
      "",
      "your turn! your turn. "
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        18,
        39
      ]
    ]
  },
  "joy in life writing from silence": {
    "sourceFile": "Transformation transformational what is life right a question of.txt",
    "contextLines": [
      "Transformation.  transformational.  what is life, right?",
      "a question of tomorrow, maybe.  This is nervousness writing from fear.  This is worry writing for wonder. This is the joy in life writing from silence. This is what that is.￼",
      "",
      "----"
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        118,
        150
      ]
    ]
  },
  "fear is all around me": {
    "sourceFile": "Grace 2.txt",
    "contextLines": [
      "Gunslinger",
      "Gunrunner",
      "How can I think when fear is all around me ",
      "How can I plan when fear is all around me ",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        21,
        42
      ]
    ]
  },
  "dripping with shame": {
    "sourceFile": "What curse is this.txt",
    "contextLines": [
      "chasing chasing chasing chasing",
      "and judging judging judging judging ",
      "dripping with shame ",
      "",
      "Now cornered it asks"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        19
      ]
    ]
  },
  "chasing chasing and judging judging": {
    "sourceFile": "What curse is this.txt",
    "contextLines": [
      "What curse is this ",
      "This dear mind of mind",
      "chasing chasing chasing chasing",
      "and judging judging judging judging ",
      "dripping with shame ",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        0,
        31
      ],
      [
        0,
        19
      ]
    ]
  },
  "kindness in my heart": {
    "sourceFile": "I feel this fear in my heart.txt",
    "contextLines": [
      "Sweet, broken twisted versions of myself ",
      "And I try to smile",
      "Kindness in my heart",
      "And almost to my eyes "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        20
      ]
    ]
  },
  "doubt and wonder and fear": {
    "sourceFile": "A wedding toast.txt",
    "contextLines": [
      "There would be a curious heartbreak ",
      "A terrible heartbreak ",
      "A feeling of doubt and wonder and fear and loneliness and yes wonder again but so much doubt ",
      "",
      "But somehow what I feel now "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        13,
        38
      ]
    ]
  },
  "godforsaken heavy doubt": {
    "sourceFile": "A wedding toast.txt",
    "contextLines": [
      "With maybe a little more space for awe",
      "Mixed in",
      "Where that godforsaken heavy doubt used to be. ",
      "",
      "To you, my friends, all the love in the world.  "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        11,
        34
      ]
    ]
  },
  "heart feels heavy": {
    "sourceFile": "Shine to me now.txt",
    "contextLines": [
      "Let me push forward the new",
      "‘Oh yes this god I cry’",
      "My heart feels heavy as I search this confusion ",
      "Am I",
      "Am this "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        3,
        20
      ]
    ]
  },
  "I hide in your anger": {
    "sourceFile": "I know I tried too much.txt",
    "contextLines": [
      "\t\t  choose safety ",
      "\t\t      ",
      "I hide in your anger. ",
      "",
      "Who hurt you so much"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        20
      ]
    ]
  },
  "quiet apprehension": {
    "sourceFile": "To be trapped in these walls.txt",
    "contextLines": [
      "Are the woods still there, if your heart cannot see them? \\",
      "Is the sound still the same \\",
      "Quiet apprehension, that the Apex predator has grown beyond his food constraints? \\",
      "Is the sound still the same \\",
      "tip toeing mice, we wait \\"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        18
      ]
    ]
  },
  "fearful to shine too bright": {
    "sourceFile": "In this country.txt",
    "contextLines": [
      "In this country ",
      "I have been tolerated ",
      "Fearful to shine too bright ",
      "Least I be thrown amongst",
      "The other misfits "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        27
      ]
    ]
  },
  "feel so trapped": {
    "sourceFile": "I feel so trapped.txt",
    "contextLines": [
      "I feel so trapped ",
      "Walls caving in",
      "Artwork a mockery "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        2,
        17
      ]
    ]
  },
  "wonder always been subjugated by shame": {
    "sourceFile": "There is a memory I have a day I once got lost.txt",
    "contextLines": [
      "",
      "",
      "Perhaps that moment that followed that glorious few forgotten moments of wonder on that swing ate those moments of glory. Hasn’t fear always eaten moments of glory? Hasn’t wonder always been subjugated by shame? ",
      "",
      "Shame came calling, when the world bore witness to my mother’s fear. Wonder, fear and the rush of warmth masquerading as joy as equilibrium drives to be restored when the cause has been rectified. Blessed we are when we are young, that the artifacts of these moments are swept up easily. Age leaves more and more notches and creases, places to gather detritus, harder for equilibrium to be restored."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        172,
        210
      ]
    ]
  },
  "I am tired of being tired": {
    "sourceFile": "Sometimes 2.txt",
    "contextLines": [
      "I feel like an intersection of regrets and what could have been ",
      "Sometimes ",
      "I am tired of being tired ",
      "Sometimes"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        25
      ]
    ]
  },
  "a tremor on the breath": {
    "sourceFile": "What coukd happen .txt",
    "contextLines": [
      "I feel a nervousness so palpable ",
      "It comes like a shake ",
      "A tremor on the breath ",
      "That moment",
      "When you wait for the door to close "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        22
      ]
    ]
  },
  "longing creating emptiness": {
    "sourceFile": "Is this love.txt",
    "contextLines": [
      "Is this love ",
      "Is this love ",
      "This longing creating emptiness in my chest",
      "Is this longing ",
      "This missing of your voice"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        5,
        31
      ]
    ]
  },
  "walls caving in": {
    "sourceFile": "I feel so trapped.txt",
    "contextLines": [
      "I feel so trapped ",
      "Walls caving in",
      "Artwork a mockery ",
      "Who can make space "
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        15
      ]
    ]
  },
  "I robbed myself of pleasure": {
    "sourceFile": "(this) so.txt",
    "contextLines": [
      "In doing ",
      "(this) so",
      "I robbed myself of pleasure ",
      "to make money ",
      "for (this)"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        27
      ]
    ]
  },
  "lest my eyes betray me": {
    "sourceFile": "I stop dead.txt",
    "contextLines": [
      "I stop dead ",
      "Least my eyes betray me ",
      "And turn my attention quick ",
      "To a branch "
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        24
      ]
    ]
  },
  "tightness in my chest": {
    "sourceFile": "I had half a banana.txt",
    "contextLines": [
      "",
      "And I feel this cold",
      "Tightness in my chest that warns me against breathing too deeply ",
      "And sweat just painting my forehead so ",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        21
      ]
    ]
  },
  "air starts to thicken": {
    "sourceFile": "the air starts to thicken.txt",
    "contextLines": [
      "the air starts to thicken",
      "and you feel an overwhelming exhaustion ",
      "that creeps it’s way forward "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        4,
        25
      ]
    ]
  },
  "tight rage of having something taken": {
    "sourceFile": "It is the fireceness of having been wronged.txt",
    "contextLines": [
      "And then had it closed ",
      "Glsss come opaque ",
      "The tight rage of having something taken away ",
      "That you had grown to want ",
      "To feel as part of yours "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        4,
        40
      ]
    ]
  },
  "in the dark place nothing is right": {
    "sourceFile": "in the dark place, nothing is right.txt",
    "contextLines": [
      "in the dark place, nothing is right",
      "there are no right words to say",
      "there is no way to ask for help"
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        35
      ]
    ]
  },
  "ebbing of the will to live": {
    "sourceFile": "There comes a point one chooses death.txt",
    "contextLines": [
      "Not from loss of blood. \\",
      "\\",
      "It is that ebbing of the will to live that brings death. \\",
      "That weariness that grows, \\",
      "Deep in each cell, \\"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        11,
        37
      ]
    ]
  },
  "chronic sort of ache": {
    "sourceFile": "Today.txt",
    "contextLines": [
      "",
      "There’s an ache, ",
      "the chronic sort of ache ",
      "that brings weary, \t\t",
      "chases moments brought by calm allusions before it-- "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        4,
        24
      ]
    ]
  },
  "what a curse to be an island": {
    "sourceFile": "Today.txt",
    "contextLines": [
      "",
      "Exclaim:",
      "What a curse, to be an island.",
      "",
      "Or maybe"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        29
      ]
    ]
  },
  "feel not to feel": {
    "sourceFile": "I know I tried too much.txt",
    "contextLines": [
      "I can’t be hurt ",
      "   If I",
      "       Feel not to feel ",
      "        This",
      "           Feeling"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        7,
        23
      ]
    ]
  },
  "pain of the undone": {
    "sourceFile": "Pierre de Coubertin.txt",
    "contextLines": [
      "What we feel is the pain of the undone. The action not taken, the anxiety of the wonder not had. There’s a terrible shaking that comes with these feelings sometimes an uncontrollable quaking. Maybe I act now because I can’t act in this life. Maybe I act now to myself and to God. ",
      "",
      "Maybe my breathing patterns are not quite right, this morning, this day, this night. "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        20,
        38
      ]
    ]
  },
  "sit with the unease": {
    "sourceFile": "Pierre de Coubertin.txt",
    "contextLines": [
      "Perform your prescribed duty, and let the rest happen as it will. ",
      "",
      "Sit with the unease. ",
      "Take no action. ",
      "Grow stronger for your restraint. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        19
      ]
    ]
  },
  "dear heart close heart": {
    "sourceFile": "Do you have words you my dear.txt",
    "contextLines": [
      "Do you have words you my dear",
      "My inner heart shadow self",
      "Dear heart close heart ",
      "Worrier ",
      "Do you have words "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        22
      ]
    ]
  },
  "what will you pay for love": {
    "sourceFile": "Pierre de Coubertin.txt",
    "contextLines": [
      "Things you forgot were freedoms. Things you never dreamed were freedoms. Things you thought you got to have just for being alive. ",
      "",
      "What will you pay for love.",
      "What will you pay, when you can make some else pay the cost.",
      "What will you pay, when they make you really want it."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        26
      ]
    ]
  },
  "dark shadow and I": {
    "sourceFile": "A great feeling.txt",
    "contextLines": [
      "We are learning to be friends",
      "this dark shadow ",
      "and I ",
      "To play",
      "find fun "
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        5,
        17
      ],
      [
        0,
        5
      ]
    ]
  },
  "the kind they like to say abides": {
    "sourceFile": "Its a deep fear.txt",
    "contextLines": [
      "It’s a deep fear",
      "the kind they like to say abides",
      "those [people] who make decisions about what a feeling feels",
      "pink wasn’t pink till it was named "
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        32
      ]
    ]
  },
  "nervousness writing from fear": {
    "sourceFile": "Transformation transformational what is life right a question of.txt",
    "contextLines": [
      "Transformation.  transformational.  what is life, right?",
      "a question of tomorrow, maybe.  This is nervousness writing from fear.  This is worry writing for wonder. This is the joy in life writing from silence. This is what that is.￼",
      "",
      "----"
    ],
    "fragmentLineIndex": 1,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        40,
        69
      ]
    ]
  },
  "rhetorical questions are cold comfort": {
    "sourceFile": "I’m in fear.txt",
    "contextLines": [
      "But what will I do when you are gone",
      "",
      "Rhetorical questions are cold comfort ",
      "Like the spray of the waves of the inland sea, a little less salty",
      "A little more cold "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        37
      ]
    ]
  },
  "safety through blocking the air": {
    "sourceFile": "There is a memory I have a day I once got lost.txt",
    "contextLines": [
      "To change the images, easy, but to make the story? How do we make a story when there was none? How do we tell a truth when it is not our memory we draw from? When do we create the truth to seed the memory? When does the building made of artifice creak and fall?",
      "In this memory, the creak was still gentle. It was the grumble of the wood that was still doing its assigned purpose, not that groan of a tool at its capacity. The groan of something at the end of its line. The groan of despair, before the sharp break of failure. ",
      "The creak was gentle. It was a soft creak, and there was a soft breeze, the kind generated by a swing when there is no room for the air to grow its own strength. The kind generated when there are 4 walls that hover close and box the world in. The kind that creates safety through keeping out the untoward. Safety through blocking the air.",
      "",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        306,
        337
      ]
    ]
  },
  "let go your catch": {
    "sourceFile": "These tensions in my back.txt",
    "contextLines": [
      "",
      "I am sorry I tried to hide from you, true self. Forgive me please ",
      "Let go your catch ",
      "",
      "Let be your squeeze "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        17
      ]
    ]
  },
  "change or die says the rain": {
    "sourceFile": "the light sings to me in the.txt",
    "contextLines": [
      "What do they think, buffeted by wind and water, berated by flying bodies?",
      "",
      "change or die, says the rain. ",
      "",
      "drrrrrrrrrrrum, drrrrrrrrrrum, drrrrrum. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        28
      ]
    ]
  },
  "get get get and let me be": {
    "sourceFile": "Cold spirits.txt",
    "contextLines": [
      "You ruminate ",
      "(in my bones)",
      "Get get get ",
      "(And let me be). ",
      "Cold wind and dark brows ",
      "(I wonder)"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        0,
        12
      ],
      [
        0,
        14
      ]
    ]
  },
  "for fucks sake I will": {
    "sourceFile": "There was some.txt",
    "contextLines": [
      "To find play in pushing the immutable ",
      "I’ll build you a new dawn ",
      "For fucks sake, i will. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        22
      ]
    ]
  },
  "cause youre a fucking poet": {
    "sourceFile": "I feel sad about endings.txt",
    "contextLines": [
      "Like when it’s too humid for your hair ",
      "It’s hard to keep brushing your teeth ",
      "Cause you’re a fucking poet ",
      "",
      "You gotta be writing poetry while you’re trying to fucking brush your teeth "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        28
      ]
    ]
  },
  "let the guillotine come": {
    "sourceFile": "I listen.txt",
    "contextLines": [
      "Nah man maybe it’s better\\",
      "\\",
      "Let the guillotine come in the night\\",
      "Sharp strokes and sharp blades \\",
      "Exhaust not my precious store of hope. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        23
      ]
    ]
  },
  "a deep sigh and the breathing slowed": {
    "sourceFile": "Testorone.txt",
    "contextLines": [
      "I felt sad.",
      "",
      "And then the shoulders dropped, eyebrows fell, brow, smoothened. A deep sigh, and the breathing slowed, head relaxed. ",
      "",
      "A slow smile, the song ends."
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        65,
        102
      ]
    ]
  },
  "I will always be a poet": {
    "sourceFile": "I will always be a poet.txt",
    "contextLines": [
      "I will always be a poet ",
      "Without my hands I will be a poet ",
      "If you sand away my finger tips I will be a poet "
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        23
      ]
    ]
  },
  "carry burdens no more": {
    "sourceFile": "The world was glad for him.txt",
    "contextLines": [
      "May your rest be long ",
      "May it be quiet ",
      "And may you carry burdens no more. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        12,
        33
      ]
    ]
  },
  "let my art survive me": {
    "sourceFile": "Shine to me now.txt",
    "contextLines": [
      "Am this ",
      "Can I be more than this ",
      "Let my art survive me, these fingers are doomed to the mortal coil ",
      "",
      "Fuck man"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        21
      ]
    ]
  },
  "kiss open the mouth of the soul": {
    "sourceFile": "I write the haunting pain.txt",
    "contextLines": [
      "And the haunting begins anew:",
      "to float down the river of the body ",
      "and kiss open the mouth of the soul.",
      " ",
      "Through pain we shall find salvation"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        4,
        35
      ]
    ]
  },
  "expand your insides till you burst": {
    "sourceFile": "Song of Tomorrow.txt",
    "contextLines": [
      "",
      "Grow tall \\",
      "Expand your insides till you burst forth \\",
      "A mirror of the older, reaching ever taller. \\",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        34
      ]
    ]
  },
  "be free my shadow": {
    "sourceFile": "In so far as there is love.txt",
    "contextLines": [
      "No shadow walks without its name. \\",
      "\\",
      "*Be free my shadow.* \\",
      "\\",
      "Take heed, my captain \\"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        1,
        18
      ]
    ]
  },
  "unbidden tears spring": {
    "sourceFile": "Unbidden tears spring.txt",
    "contextLines": [
      "Unbidden ",
      "tears spring ",
      "To my eyes",
      "To think"
    ],
    "fragmentLineIndex": 0,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        0,
        9
      ],
      [
        0,
        12
      ]
    ]
  },
  "this too will pass": {
    "sourceFile": "By the time of the third sneeze.txt",
    "contextLines": [
      "After ",
      "",
      "This too will pass",
      "As will every joy",
      "Every sorrow "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        18
      ]
    ]
  },
  "he stole the night to be his": {
    "sourceFile": "There was some.txt",
    "contextLines": [
      "He danced like a colored boy ",
      "For all his albaster skin ",
      "He stole the night to be his",
      "He captured the street ",
      "The story "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        28
      ]
    ]
  },
  "Ill build you a new dawn": {
    "sourceFile": "There was some.txt",
    "contextLines": [
      "To tease the edge of good",
      "To find play in pushing the immutable ",
      "I’ll build you a new dawn ",
      "For fucks sake, i will. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        26
      ]
    ]
  },
  "break my chains will you": {
    "sourceFile": "I write the haunting pain.txt",
    "contextLines": [
      "\t\t\tanother ",
      "",
      "Break my chains, ",
      "\twill you?",
      "Who will take this haunting of my pain. ",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 2,
    "fragmentCharRanges": [
      [
        0,
        17
      ],
      [
        0,
        9
      ]
    ]
  },
  "with my blood I will paint you": {
    "sourceFile": "I will always be a poet.txt",
    "contextLines": [
      "If you sand away my finger tips I will be a poet ",
      "If you shave my chest to expose my heart ",
      "With my blood I will paint you with poetry ",
      "",
      "~~Some are worth dying over~~ "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        30
      ]
    ]
  },
  "raised words and sharp voices": {
    "sourceFile": "We sharpen the blade.txt",
    "contextLines": [
      "We sharpen the blade",
      "*flick flick*",
      "Raised words and sharp voices ",
      "*flick flick*",
      "Honing with precision "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        29
      ]
    ]
  },
  "breathe and expand": {
    "sourceFile": "What curse is this.txt",
    "contextLines": [
      "Help",
      "",
      "Or maybe the word isn’t help. Help is what people do to you. What is the word for what you do to yourself. Let’s breathe and expand.",
      "Breathe and expand.",
      "Breathe"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        113,
        131
      ]
    ]
  },
  "oh my bruised empty dirt and grow life": {
    "sourceFile": "California 2.txt",
    "contextLines": [
      "",
      "Lets sing more your praises ",
      "Oh my bruised, empty dirt",
      "",
      "And grow life.",
      "",
      "Look mommy, how grown is your little prince. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 3,
    "fragmentCharRanges": [
      [
        0,
        25
      ],
      [
        0,
        0
      ],
      [
        0,
        13
      ]
    ]
  },
  "crookedly yearning towards the lights": {
    "sourceFile": "Song of Tomorrow.txt",
    "contextLines": [
      "Oh sing to me, you, Song of Tomorrow \\",
      "Will you grow tall \\",
      "Crookedly yearning towards the lights \\",
      "That see you and beat you \\",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        37
      ]
    ]
  },
  "animals in the night": {
    "sourceFile": "Pierre de Coubertin.txt",
    "contextLines": [
      "Are you (we (us)) an animal. Would that be so bad, to be an animal. ",
      "",
      "Let’s go be animals in the night. ",
      "",
      "We frolic wildly. There’s an amusement in an aggressive pantomiming of sex that has existed across generations. We see it reoccur time and time again. Across cultures and situations. Could it be genetic?"
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        12,
        32
      ]
    ]
  },
  "shift rocks and pull mountains": {
    "sourceFile": "Do you have words you my dear.txt",
    "contextLines": [
      "speak speak speak ",
      "and now tell strong sister:",
      "to shift rocks and pull mountains!",
      "Hearts a’fly out ‘o-ward!",
      "out of deep valley and dark pit: "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        3,
        33
      ]
    ]
  },
  "hearts fly towards you": {
    "sourceFile": "Do you have words you my dear.txt",
    "contextLines": [
      "Strong sister",
      "You shift rocks and pull mountains",
      "Hearts fly towards you ",
      "You are the most beautiful parts of me",
      "Twirling a dance of torture and pain "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        22
      ]
    ]
  },
  "wind come to howl": {
    "sourceFile": "A leaf come to hi.txt",
    "contextLines": [
      "\t\t\t\t\tto win ",
      "",
      "Wind come to howl, come to chase away the leaves.",
      "",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        17
      ]
    ]
  },
  "churn churn CHURN": {
    "sourceFile": "California 2.txt",
    "contextLines": [
      "Oh bruised, empty, raw dirt ",
      "Let us sing more your praises ",
      "Churn, churn, CHURN!",
      "And grow life as I command. ",
      "Look mommy, how grown is your little prince. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        19
      ]
    ]
  },
  "come watch creepers creep": {
    "sourceFile": "Have you watched creepers creep.txt",
    "contextLines": [
      "",
      "-----",
      "Come watch creepers creep",
      "See this dedication!",
      "\tTrials and tribulations bear witness "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        25
      ]
    ]
  },
  "used to crumble all foundations": {
    "sourceFile": "Have you watched creepers creep.txt",
    "contextLines": [
      "Applaud the dedication, these creepers.",
      "Evolved to find the smallest of holes ",
      "And used to crumble all foundations.",
      " ",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        4,
        35
      ]
    ]
  },
  "meat for the mind": {
    "sourceFile": "Pierre de Coubertin.txt",
    "contextLines": [
      "You. You. We know you. You come to bribe the animal. How can you dress so beautifully. How can you seduce us so. Don’t you know we are playing at being animals in the night. They gave us meat for minds. Quirks of personality made machine made content made minds. ",
      "",
      "Meat for the mind.",
      "",
      "Did you know a single man dreamed of there again being Olympics. "
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        0,
        17
      ]
    ]
  },
  "play the game to win": {
    "sourceFile": "A leaf come to hi.txt",
    "contextLines": [
      "\t\tto dance without your heart",
      "",
      "\t\tto play the game to win",
      "",
      ""
    ],
    "fragmentLineIndex": 2,
    "fragmentLineCount": 1,
    "fragmentCharRanges": [
      [
        5,
        25
      ]
    ]
  }
}
