// Unified phrase pool — each phrase scored on 4 axes
// Axes: [sublimate/crystallise, grip/release, echo/ignite, smother/howl]
// -1 = first side (sublimate, grip, echo, smother)
// +1 = second side (crystallise, release, ignite, howl)
export const phrases = [
  // --- sublimate (28) ---
  { text: "thoughts are just air",                            axes: [-0.9, 0.6, 0, 0.2] },
  { text: "whispered filament silvered to light",             axes: [-0.8, 0.3, -0.2, 0] },
  { text: "the darkness had flown",                           axes: [-0.6, 0.4, -0.3, 0.3] },
  { text: "faded from view",                                  axes: [-0.7, 0.2, -0.5, 0.1] },
  { text: "sun chasing luminance",                         axes: [-0.6, 0.4, 0, -0.2] },
  { text: "flecks of power in the air",                           axes: [-0.7, 0.5, 0, 0.1] },
  { text: "invisible to all there was",                       axes: [-0.8, 0.1, -0.4, -0.3] },
  { text: "dissipates like smoke",                            axes: [-0.8, 0.5, -0.1, 0.2] },
  { text: "memory flickers",                                  axes: [-0.5, 0.2, -0.8, -0.1] },
  { text: "shuffle off o' mortal coil",                     axes: [-0.9, 0.3, -0.1, 0.4] },
  { text: "spirits unmoored from flesh",                      axes: [-0.9, 0.6, -0.3, 0.5] },
  { text: "mist flowing towards the door",                    axes: [-0.8, 0.5, 0, 0.1] },
  { text: "protective womb mimicry",                          axes: [-0.6, -0.3, -0.2, -0.4] },
  { text: "as it coalesces from eternity",                    axes: [-0.9, 0.4, -0.1, 0.1] },
  { text: "the white ghost of memory",                        axes: [-0.8, 0.2, -0.5, -0.1] },
  { text: "in the moments between moments",                   axes: [-0.7, 0.3, -0.1, -0.1] },
  { text: "power dissipates",                  axes: [-0.7, 0.2, -0.2, 0.3] },
  { text: "the echo of power is power",                       axes: [-0.5, -0.1, -0.3, -0.1] },
  { text: "soft and warm like a memory",                      axes: [-0.5, 0.2, -0.6, -0.1] },
  { text: "strange haze over the valley",                     axes: [-0.6, 0.3, -0.2, -0.1] },
  { text: "a ghost of ideas long past",                       axes: [-0.7, 0.3, -0.7, -0.1] },
  { text: "pale pink before dawn",                            axes: [-0.7, 0.4, 0, 0.1] },
  { text: "the form fades",                                   axes: [-0.8, 0.3, -0.3, -0.1] },
  { text: "this is a world of air",                           axes: [-0.9, 0.5, 0, 0.1] },
  { text: "gap between breath and emptiness",                 axes: [-0.8, 0.4, -0.1, -0.2] },
  { text: "leave wonder wondering",                           axes: [-0.6, 0.3, -0.2, 0] },
  { text: "to fade into light",                               axes: [-0.9, 0.5, 0, 0.2] },
  { text: "coalesced from eternity made water",               axes: [-0.8, 0.4, -0.2, 0] },
  // --- crystallise (30) ---
  { text: "sharp strokes and sharp blades",                   axes: [0.9, -0.2, 0, -0.3] },
  { text: "scars on his wrist burn",                          axes: [0.9, -0.3, -0.4, -0.6] },
  { text: "sinew rots to bone",                               axes: [0.9, -0.5, -0.2, -0.3] },
  { text: "skin ready to be torn",                            axes: [0.8, -0.2, 0.1, -0.5] },
  { text: "bones get tired",                                  axes: [0.7, -0.5, -0.2, -0.4] },
  { text: "muscles were shaking",                             axes: [0.8, -0.4, 0.2, -0.5] },
  { text: "cold wind sends hair erect",                       axes: [0.6, -0.2, 0.3, -0.1] },
  { text: "watching the blood / watching it coagulate and flow",                       axes: [0.7, -0.1, -0.3, 0.1] },
  { text: "bangles clattering in the cold",                   axes: [0.7, -0.3, -0.2, 0] },
  { text: "sever the skin and create a book",                     axes: [0.9, -0.1, 0.2, 0.3] },
  { text: "intestinal flesh and precluded winter",            axes: [0.9, -0.3, -0.1, -0.2] },
  { text: "dead animals dot the roots",                       axes: [0.8, -0.4, -0.2, -0.1] },
  { text: "so soft so wet so sweet",                          axes: [0.7, 0.3, 0.4, 0.2] },
  { text: "sharpen the blade",               axes: [0.9, -0.3, 0, -0.1] },
  { text: "pink to show intestinal flesh",                    axes: [0.8, -0.1, 0.1, 0.1] },
  { text: "they catch me they caught me",                       axes: [0.7, -0.3, 0.1, -0.8] },
  { text: "tensions in my back",                              axes: [0.8, -0.4, 0.2, -0.7] },
  { text: "pit grows in stomach",                             axes: [0.5, -0.3, 0.1, -0.9] },
  { text: "wolves in the fire light",                         axes: [0.7, -0.2, 0.3, 0] },
  { text: "a curtain of snow ready to slip",                  axes: [0.6, 0.2, 0, -0.1] },
  { text: "earth torn asunder",                               axes: [0.9, -0.4, 0, 0.2] },
  { text: "slight thud of a delicate body",                   axes: [0.7, -0.1, 0, -0.3] },
  { text: "dagger shaped",                                    axes: [0.9, -0.2, 0, -0.2] },
  { text: "rip tear chew",                                    axes: [0.9, -0.4, 0.3, 0.5] },
  { text: "bare feet on nails",                               axes: [0.8, -0.5, 0.2, -0.3] },
  { text: "twirling a dance of torture",                      axes: [0.7, -0.2, 0, -0.4] },
  { text: "writhing under you",                               axes: [0.8, -0.4, 0.4, -0.1] },
  { text: "cold in these waters",                             axes: [0.6, -0.3, -0.1, -0.2] },
  { text: "tendril a whisper of meat",                        axes: [0.7, -0.1, 0, -0.1] },
  { text: "breaking up the soil",                             axes: [0.7, -0.3, 0.2, 0.1] },
  // --- grip (26) ---
  { text: "in my back I am the earth",                            axes: [0.2, -0.9, 0, -0.2] },
  { text: "rooted in a climb of dirt",                         axes: [0.1, -0.9, -0.2, -0.1] },
  { text: "drink deeply of the grass",                        axes: [-0.1, -0.7, 0.2, 0.1] },
  { text: "cedars still walked",                              axes: [0, -0.8, -0.4, 0] },
  { text: "grow tall my green children",                         axes: [-0.1, -0.8, 0.3, 0.1] },
  { text: "soldiers fighting against the slow erosion to entropy",                  axes: [0.2, -0.7, -0.3, -0.4] },
  { text: "feathers quiver in the breeze",                        axes: [-0.3, -0.4, 0.2, 0.2] },
  { text: "still they would remember",                            axes: [0.1, -0.8, -0.7, -0.1] },
  { text: "monsoon brings the green",                         axes: [-0.1, -0.7, 0.2, 0.3] },
  { text: "tall trees tall pines",                            axes: [0, -0.8, -0.1, 0] },
  { text: "chained by choices",                               axes: [0.4, -0.8, -0.1, -0.5] },
  { text: "my self is bound together",                              axes: [0.2, -0.9, 0.1, -0.2] },
  { text: "hold on I still want you",                         axes: [0.3, -0.8, -0.2, 0.1] },
  { text: "a morning with the bamboo",                          axes: [0, -0.8, 0.1, 0.1] },
  { text: "caught and snared",                                axes: [0.3, -0.8, 0, -0.4] },
  { text: "these ties that bind",                             axes: [0.1, -0.7, -0.1, -0.3] },
  { text: "substances coming into my shoes",                        axes: [0.3, -0.6, 0.3, 0] },
  { text: "that thing which binds you",                       axes: [0.1, -0.7, -0.1, -0.3] },
  { text: "you are caught and snared",                        axes: [0.3, -0.8, 0, -0.4] },
  { text: "spirit in my bones",                          axes: [0.2, -0.6, -0.4, -0.5] },
  { text: "pressed against mine",                             axes: [0.4, -0.7, 0.3, -0.1] },
  { text: "your breath caught in my air",                     axes: [0.2, -0.8, 0.2, -0.1] },
  { text: "stitch my heart with yours",                       axes: [0.3, -0.8, 0.1, -0.2] },
  { text: "touch in a certain way to give remembrance",                          axes: [0.1, -0.7, -0.5, -0.1] },
  { text: "gravitational pull between us",                    axes: [0, -0.9, -0.1, -0.2] },
  { text: "be mine forever never come near me again",                      axes: [0.2, -0.9, 0, -0.4] },
  // --- release (25) ---
  { text: "dolphins a-dancing",                               axes: [-0.1, 0.9, 0.3, 0.4] },
  { text: "dancing now on the morning wind",                          axes: [-0.3, 0.9, 0.1, 0.4] },
  { text: "flutter of the leaves",                            axes: [-0.3, 0.7, 0.1, 0.2] },
  { text: "the mind is adrift",                               axes: [-0.4, 0.8, 0, 0.1] },
  { text: "floating down a river",                            axes: [-0.3, 0.9, 0, 0.3] },
  { text: "if only I could spin fast enough",                       axes: [0, 0.9, 0.2, 0.4] },
  { text: "drifting in darkness",                             axes: [-0.4, 0.8, -0.2, -0.3] },
  { text: "leaves dancing a tiny dance",                      axes: [-0.2, 0.7, 0.2, 0.2] },
  { text: "swim to me swim to me",                            axes: [0, 0.8, 0.3, 0.3] },
  { text: "water nymphs come up from the river",                             axes: [-0.3, 0.7, -0.3, 0.2] },
  { text: "let be your squeeze",                              axes: [-0.1, 0.8, 0, 0.5] },
  { text: "birth me again",                                   axes: [-0.1, 0.7, 0.3, 0.5] },
  { text: "under a waterfall in the sun",                     axes: [-0.1, 0.8, 0.5, 0.4] },
  { text: "we could outspin the world",                       axes: [-0.1, 0.8, 0.1, 0.5] },
  { text: "sky dreaming lovers enchanted",                    axes: [-0.4, 0.8, -0.2, 0.1] },
  { text: "dancing to and fro",                               axes: [-0.1, 0.8, 0.2, 0.3] },
  { text: "whole field a quaver",                             axes: [-0.3, 0.7, 0.1, 0.1] },
  { text: "I can hear it now",                         axes: [-0.5, 0.6, 0.2, 0.2] },
  { text: "whisk away the warmth",                            axes: [-0.2, 0.7, 0, 0.3] },
  { text: "unbidden / tears spring / to my eyes",               axes: [-0.2, 0.7, 0.2, 0.8] },
  { text: "soft fingers wandering wondering",                 axes: [-0.1, 0.6, 0, 0.1] },
  { text: "what a gift to be on an island",                   axes: [-0.2, 0.8, 0.1, 0.3] },
  { text: "we frolic wildly",                                 axes: [-0.1, 0.9, 0.4, 0.7] },
  { text: "come out you play",                                axes: [-0.1, 0.8, 0.3, 0.4] },
  { text: "dance away the chlorophyll",                       axes: [-0.3, 0.7, 0.2, 0.3] },
  // --- echo (27) ---
  { text: "give me back my memories",                         axes: [0, 0, -0.9, -0.5] },
  { text: "remembrance of your laugh",                        axes: [-0.2, 0.1, -0.9, -0.1] },
  { text: "a time long ago",                                  axes: [-0.2, 0, -0.9, -0.1] },
  { text: "memories you wish you had",                        axes: [-0.2, 0.1, -0.8, -0.5] },
  { text: "lost to a distant memory",                         axes: [-0.4, 0.2, -0.9, -0.2] },
  { text: "once we were unforgettable",                       axes: [0, 0.1, -0.9, -0.1] },
  { text: "who mourns a lost word",                           axes: [-0.3, 0, -0.8, -0.4] },
  { text: "something long thought forgotten",                 axes: [-0.3, 0, -0.9, -0.3] },
  { text: "color lost to a distant memory",                     axes: [-0.4, 0.1, -0.9, -0.2] },
  { text: "words we left when we left",                       axes: [-0.2, 0.1, -0.8, -0.2] },
  { text: "when you were young",                              axes: [0, 0, -0.9, -0.2] },
  { text: "sometimes good morning means goodbye",             axes: [0.1, 0.1, -0.7, -0.2] },
  { text: "there was joy once",                               axes: [-0.1, 0, -0.8, -0.1] },
  { text: "everything I build will turn to dust",             axes: [0.2, 0.1, -0.7, -0.1] },
  { text: "relics of my heart",                               axes: [0, -0.1, -0.8, -0.3] },
  { text: "these shadows will be all that remain",            axes: [-0.2, 0, -0.8, -0.2] },
  { text: "remembrance owned by others",                      axes: [0, 0, -0.8, -0.4] },
  { text: "memories mine own",                                axes: [0, -0.1, -0.9, -0.2] },
  { text: "their forever why",                                axes: [-0.1, 0.1, -0.7, -0.1] },
  { text: "it reminds me of home",                            axes: [0, -0.2, -0.8, -0.1] },
  { text: "creeping death laughing all the while",            axes: [0.3, -0.1, -0.6, 0.1] },
  { text: "morning of the small birds",                       axes: [-0.1, 0.1, -0.7, 0] },
  { text: "mourning of the crows",                            axes: [0.1, -0.1, -0.8, -0.2] },
  { text: "is that yours or is that mine",                    axes: [0, -0.1, -0.7, -0.2] },
  { text: "it used to be me",                                 axes: [0, 0, -0.9, -0.3] },
  { text: "fear always eaten moments of glory",               axes: [0.1, -0.2, -0.7, -0.4] },
  { text: "today is a memory that someone dreamed up",             axes: [-0.3, 0.1, -0.8, 0] },
  // --- ignite (27) ---
  { text: "this moment this one",                             axes: [0.1, -0.1, 0.9, 0] },
  { text: "forever is now",                                   axes: [-0.1, 0, 0.9, 0.2] },
  { text: "today is enough",                                  axes: [0.1, -0.2, 0.8, 0.3] },
  { text: "moments of grace",                                 axes: [-0.2, 0.1, 0.9, 0.3] },
  { text: "alive alive we live",                              axes: [0.3, 0.3, 0.9, 0.5] },
  { text: "pink fucking mountains",                           axes: [0.3, 0.4, 0.9, 0.7] },
  { text: "light was born",                                   axes: [-0.3, 0.4, 0.8, 0.3] },
  { text: "the sublime joy of being naked",                   axes: [0.2, 0.5, 0.8, 0.5] },
  { text: "I forgot I was magic",                             axes: [-0.1, 0.2, 0.7, 0.4] },
  { text: "here you come here you come",                      axes: [0.1, 0.2, 0.8, 0.2] },
  { text: "this is why we live",                              axes: [0, 0, 0.9, 0.4] },
  { text: "cold feet find wonder",                            axes: [0.3, -0.1, 0.7, 0.2] },
  { text: "light is designed for wonder",                     axes: [-0.3, 0.3, 0.8, 0.2] },
  { text: "chase some light and find wonder",                 axes: [-0.2, 0.4, 0.8, 0.3] },
  { text: "top of my head is tingling",                       axes: [0.4, -0.1, 0.8, 0] },
  { text: "blessed to see movement",                          axes: [0, 0.2, 0.8, 0.3] },
  { text: "completely happy only that",                       axes: [0, 0.1, 0.8, 0.4] },
  { text: "this is why we are alive",                         axes: [0, 0, 0.9, 0.4] },
  { text: "became wonder",                                    axes: [-0.3, 0.3, 0.8, 0.2] },
  { text: "life and love be all you do",                      axes: [0, 0.1, 0.8, 0.5] },
  { text: "I see yellow in the green",                        axes: [0.2, 0.1, 0.7, 0.2] },
  { text: "eyes chasing the sky",                             axes: [-0.2, 0.3, 0.7, 0.2] },
  { text: "child of wonder",                                  axes: [-0.1, 0.2, 0.8, 0.3] },
  { text: "shimmer me brighter",                              axes: [-0.1, 0.3, 0.9, 0.4] },
  { text: "shimmer of red against the sun",                   axes: [0.2, 0.2, 0.8, 0.2] },
  { text: "firstly you are first",                            axes: [0.1, 0, 0.7, 0.3] },
  { text: "joy in life writing from silence",                 axes: [-0.2, 0.1, 0.8, 0.1] },
  // --- smother (35) ---
  { text: "fear is all around me",                            axes: [0.2, -0.1, 0.1, -0.9] },
  { text: "dripping with shame",                              axes: [0.3, -0.2, 0, -0.9] },
  { text: "chasing chasing and judging judging",                          axes: [0.2, 0.1, 0, -0.8] },
  { text: "kindness in my heart",                            axes: [0.2, -0.2, -0.1, -0.8] },
  { text: "doubt and wonder and fear",                        axes: [0, 0.1, 0, -0.9] },
  { text: "godforsaken heavy doubt",                          axes: [0.3, -0.3, 0, -0.9] },
  { text: "heart feels heavy",                                axes: [0.3, -0.3, 0, -0.8] },
  { text: "I hide in your anger",                             axes: [0.1, -0.3, -0.1, -0.8] },
  { text: "quiet apprehension",                               axes: [0.1, -0.1, 0.1, -0.7] },
  { text: "fearful to shine too bright",                      axes: [-0.1, 0, 0, -0.8] },
  { text: "feel so trapped",                                  axes: [0.4, -0.4, 0.1, -0.9] },
  { text: "wonder always been subjugated by shame",                       axes: [-0.1, -0.1, 0, -0.8] },
  { text: "I am tired of being tired",                        axes: [0.3, -0.2, 0.1, -0.7] },
  { text: "a tremor on the breath",                           axes: [0.2, -0.1, 0, -0.6] },
  { text: "longing creating emptiness",                       axes: [0.3, -0.1, -0.2, -0.8] },
  { text: "walls caving in",                                  axes: [0.7, -0.6, 0, -0.9] },
  { text: "I robbed myself of pleasure",                      axes: [0.2, -0.1, -0.1, -0.6] },
  { text: "lest my eyes betray me",                           axes: [0.1, -0.3, -0.1, -0.7] },
  { text: "tightness in my chest",                            axes: [0.5, -0.3, 0.1, -0.8] },
  { text: "air starts to thicken",                            axes: [0.3, -0.2, 0.1, -0.7] },
  { text: "tight rage of having something taken",             axes: [0.5, -0.3, -0.1, -0.8] },
  { text: "in the dark place nothing is right",               axes: [0.1, -0.2, -0.2, -0.9] },
  { text: "ebbing of the will to live",                       axes: [0.1, -0.2, -0.1, -0.7] },
  { text: "chronic sort of ache",                             axes: [0.3, -0.2, -0.1, -0.8] },
  { text: "what a curse to be an island",                     axes: [0.2, -0.3, -0.2, -0.8] },
  { text: "feel not to feel",                                 axes: [0.1, -0.2, 0, -0.8] },
  { text: "pain of the undone",                               axes: [0.2, -0.1, -0.2, -0.8] },
  { text: "sit with the unease",                              axes: [0.2, -0.2, 0, -0.7] },
  { text: "dear heart close heart",                           axes: [0.1, -0.3, -0.1, -0.8] },
  { text: "what will you pay for love",                       axes: [0.2, -0.2, -0.1, -0.7] },
  { text: "dark shadow and I",                                axes: [0.1, -0.2, -0.3, -0.7] },
  { text: "the kind they like to say abides",                   axes: [0.3, -0.3, -0.1, -0.9] },
  { text: "nervousness writing from fear",                    axes: [0.2, -0.1, 0, -0.7] },
  { text: "rhetorical questions are cold comfort",                axes: [0.1, -0.1, -0.2, -0.6] },
  { text: "safety through blocking the air",                  axes: [0.2, -0.3, 0, -0.7] },
  // --- howl (32) ---
  { text: "let go your catch",                                axes: [0, 0.2, 0.1, 0.9] },
  { text: "change or die says the rain",                      axes: [0.3, 0.2, 0.4, 0.8] },
  { text: "get get get and let me be",                        axes: [0.3, 0.3, 0.3, 0.9] },
  { text: "for fucks sake I will",                            axes: [0.4, 0.1, 0.5, 0.9] },
  { text: "cause youre a fucking poet",                       axes: [0.4, 0.3, 0.5, 0.9] },
  { text: "let the guillotine come",                          axes: [0.3, 0.4, 0, 0.8] },
  { text: "a deep sigh and the breathing slowed",                       axes: [-0.3, -0.1, 0.2, 0.9] },
  { text: "I will always be a poet",                          axes: [0.1, 0.1, 0.2, 0.8] },
  { text: "carry burdens no more",                            axes: [0, 0.1, 0, 0.9] },
  { text: "let my art survive me",                            axes: [-0.1, 0.2, -0.2, 0.8] },
  { text: "kiss open the mouth of the soul",                  axes: [-0.1, 0.3, 0.3, 0.8] },
  { text: "expand your insides till you burst",               axes: [0.4, 0.3, 0.5, 0.9] },
  { text: "be free my shadow",                                axes: [-0.3, 0.5, -0.1, 0.8] },
  { text: "unbidden tears spring",                            axes: [0.1, 0.2, 0, 0.8] },
  { text: "this too will pass",                               axes: [-0.1, 0.1, 0.1, 0.8] },
  { text: "he stole the night to be his",                     axes: [0.2, -0.2, -0.1, 0.8] },
  { text: "Ill build you a new dawn",                         axes: [0.1, 0.2, 0.4, 0.9] },
  { text: "break my chains will you",                         axes: [0.3, 0.4, 0.1, 0.9] },
  { text: "with my blood I will paint you",                   axes: [0.8, -0.2, 0.3, 0.9] },
  { text: "raised words and sharp voices",                    axes: [0.6, 0, 0.1, 0.8] },
  { text: "breathe and expand",                               axes: [-0.2, 0.1, 0.3, 0.7] },
  { text: "oh my bruised empty dirt and grow life",                    axes: [0.4, -0.3, 0.3, 0.8] },
  { text: "crookedly yearning towards the lights",            axes: [-0.1, 0.1, 0.2, 0.7] },
  { text: "animals in the night",                             axes: [0.3, -0.1, 0.2, 0.8] },
  { text: "shift rocks and pull mountains",                   axes: [0.4, -0.2, 0.3, 0.9] },
  { text: "hearts fly towards you",                           axes: [0.1, 0.3, 0.3, 0.8] },
  { text: "wind come to howl",                                axes: [-0.1, 0.3, 0, 0.9] },
  { text: "churn churn CHURN",                                axes: [0.5, -0.1, 0.4, 0.9] },
  { text: "come watch creepers creep",                        axes: [0.2, 0, 0.2, 0.7] },
  { text: "used to crumble all foundations",               axes: [0.4, 0.2, 0.1, 0.9] },
  { text: "meat for the mind",                                axes: [0.5, -0.1, 0.3, 0.7] },
  { text: "play the game to win",                             axes: [0.3, 0, 0.3, 0.8] },
]

// The 4 axes (pairs)
export const axes = [
  ['sublimate', 'crystallise'],
  ['grip', 'release'],
  ['echo', 'ignite'],
  ['smother', 'howl']
]

const axisIndex = {
  sublimate: 0, crystallise: 0,
  grip: 1, release: 1,
  echo: 2, ignite: 2,
  smother: 3, howl: 3,
}

const axisSign = {
  sublimate: -1, crystallise: 1,
  grip: -1, release: 1,
  echo: -1, ignite: 1,
  smother: -1, howl: 1,
}

export function getRandomLine(choice, exclude = []) {
  const idx = axisIndex[choice]
  const sign = axisSign[choice]

  const scored = phrases
    .filter(p => !exclude.includes(p.text))
    .map(p => ({ text: p.text, score: p.axes[idx] * sign }))
    .filter(p => p.score > 0)

  if (scored.length === 0) {
    const available = phrases.filter(p => !exclude.includes(p.text))
    return available[Math.floor(Math.random() * available.length)].text
  }

  const totalWeight = scored.reduce((sum, p) => sum + p.score, 0)
  let r = Math.random() * totalWeight
  for (const p of scored) {
    r -= p.score
    if (r <= 0) return p.text
  }
  return scored[scored.length - 1].text
}
